### ISSUE TITLE
Submission of example failed

### ISSUE THREAD

**Issue by schmmd** [allenai/drop-leaderboard-example#2]
tried to make a DROP submission with the example, but I got an exception:

https://beaker.org/ex/ex_j0orx4q7r7gx/tasks/tk_9g67l6vizfz5

In case the experiment isn't visible here are the logs.

```
Experiments
Datasets
Groups
ex_j0orx4q7r7gx
Leaderboard submission leaderboard=drop type=model env=dev author=schmmd
Created 41 minutes ago by Michael Schmitz (schmmd) for Leaderboard
Total cost: $0.004 (InProgress)
TasksExperiment GraphSpec
model
evaluator
model
Failed
(History)
Finished 35 minutes ago. Ran for a minute.  Created by Michael Schmitz for Leaderboard
Description	
None
Logs	16 Lines (24.8KiB)Show Full LogDownload Full Log
Results	ds_ltus5cgo9srf
Metrics	None
Program Arguments	
./run_model.sh
Environment Variables	None
Requirements	
0 P100 GPU0 CPU0.0B Memory
Image	drop-example
Input Datasets	
Dataset ID	Mount Path
ds_y4amlwprd6nj	/drop.json
ID	tk_9g67l6vizfz5
Cost	$0.004
© 2019 The Allen Institute for Artificial Intelligence
Powered by

Releases
Terms of Use
Copy to Clipboard
2019-05-03T16:21:19.90290397Z	
	 0%|          | 0/51410373 [00:00<?, ?B/s]
	 1%|▏         | 681984/51410373 [00:00<00:08, 5850245.36B/s]
	 9%|▉         | 4736000/51410373 [00:00<00:05, 7870688.19B/s]
	18%|█▊        | 9225216/51410373 [00:00<00:04, 10458001.63B/s]
	29%|██▉       | 15121408/51410373 [00:00<00:02, 13884539.91B/s]
	40%|███▉      | 20490240/51410373 [00:00<00:01, 17855616.28B/s]
	51%|█████     | 26211328/51410373 [00:00<00:01, 22498451.05B/s]
	61%|██████▏   | 31555584/51410373 [00:00<00:00, 27227514.08B/s]
	72%|███████▏  | 37255168/51410373 [00:00<00:00, 32285569.23B/s]
	82%|████████▏ | 42289152/51410373 [00:00<00:00, 35281527.45B/s]
	92%|█████████▏| 47299584/51410373 [00:01<00:00, 38716282.14B/s]
100%|██████████|	51410373/51410373 [00:01<00:00, 45635361.33B/s]
2019-05-03T16:21:19.904559001Z	Traceback (most recent call last):
2019-05-03T16:21:19.904576292Z	  File "predict.py", line 20, in <module>
2019-05-03T16:21:19.904580953Z	    archive = load_archive(args.archive_file)
2019-05-03T16:21:19.904613179Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/models/archival.py", line 230, in load_archive
2019-05-03T16:21:19.904618515Z	    cuda_device=cuda_device)
2019-05-03T16:21:19.904622681Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 327, in load
2019-05-03T16:21:19.90462704Z	    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
2019-05-03T16:21:19.904631319Z	  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 276, in _load
2019-05-03T16:21:19.904635751Z	    model.load_state_dict(model_state)
2019-05-03T16:21:19.904639652Z	  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
2019-05-03T16:21:19.904644188Z	    self.__class__.__name__, "\n\t".join(error_msgs)))
2019-05-03T16:21:19.904648337Z	RuntimeError: Error(s) in loading state_dict for NumericallyAugmentedQaNet:
2019-05-03T16:21:19.904657808Z		Missing key(s) in state_dict: "_phrase_layer._encoder_blocks.0._conv_norm_layers.0.weight", "_phrase_layer._encoder_blocks.0._conv_norm_layers.0.bias", "_phrase_layer._encoder_blocks.0._conv_norm_layers.1.weight", "_phrase_layer._encoder_blocks.0._conv_norm_layers.1.bias", "_phrase_layer._encoder_blocks.0._conv_norm_layers.2.weight", "_phrase_layer._encoder_blocks.0._conv_norm_layers.2.bias", "_phrase_layer._encoder_blocks.0._conv_norm_layers.3.weight", "_phrase_layer._encoder_blocks.0._conv_norm_layers.3.bias", "_phrase_layer._encoder_blocks.0._conv_layers.0.1.weight", "_phrase_layer._encoder_blocks.0._conv_layers.0.1.bias", "_phrase_layer._encoder_blocks.0._conv_layers.0.2.weight", "_phrase_layer._encoder_blocks.0._conv_layers.0.2.bias", "_phrase_layer._encoder_blocks.0._conv_layers.1.1.weight", "_phrase_layer._encoder_blocks.0._conv_layers.1.1.bias", "_phrase_layer._encoder_blocks.0._conv_layers.1.2.weight", "_phrase_layer._encoder_blocks.0._conv_layers.1.2.bias", "_phrase_layer._encoder_blocks.0._conv_layers.2.1.weight", "_phrase_layer._encoder_blocks.0._conv_layers.2.1.bias", "_phrase_layer._encoder_blocks.0._conv_layers.2.2.weight", "_phrase_layer._encoder_blocks.0._conv_layers.2.2.bias", "_phrase_layer._encoder_blocks.0._conv_layers.3.1.weight", "_phrase_layer._encoder_blocks.0._conv_layers.3.1.bias", "_phrase_layer._encoder_blocks.0._conv_layers.3.2.weight", "_phrase_layer._encoder_blocks.0._conv_layers.3.2.bias", "_phrase_layer._encoder_blocks.0.attention_norm_layer.weight", "_phrase_layer._encoder_blocks.0.attention_norm_layer.bias", "_phrase_layer._encoder_blocks.0.attention_layer._combined_projection.weight", "_phrase_layer._encoder_blocks.0.attention_layer._combined_projection.bias", "_phrase_layer._encoder_blocks.0.attention_layer._output_projection.weight", "_phrase_layer._encoder_blocks.0.attention_layer._output_projection.bias", "_phrase_layer._encoder_blocks.0.feedforward_norm_layer.weight", "_phrase_layer._encoder_blocks.0.feedforward_norm_layer.bias", "_phrase_layer._encoder_blocks.0.feedforward._linear_layers.0.weight", "_phrase_layer._encoder_blocks.0.feedforward._linear_layers.0.bias", "_phrase_layer._encoder_blocks.0.feedforward._linear_layers.1.weight", "_phrase_layer._encoder_blocks.0.feedforward._linear_layers.1.bias", "_modeling_layer._encoder_blocks.0._conv_norm_layers.0.weight", "_modeling_layer._encoder_blocks.0._conv_norm_layers.0.bias", "_modeling_layer._encoder_blocks.0._conv_norm_layers.1.weight", "_modeling_layer._encoder_blocks.0._conv_norm_layers.1.bias", "_modeling_layer._encoder_blocks.0._conv_layers.0.1.weight", "_modeling_layer._encoder_blocks.0._conv_layers.0.1.bias", "_modeling_layer._encoder_blocks.0._conv_layers.0.2.weight", "_modeling_layer._encoder_blocks.0._conv_layers.0.2.bias", "_modeling_layer._encoder_blocks.0._conv_layers.1.1.weight", "_modeling_layer._encoder_blocks.0._conv_layers.1.1.bias", "_modeling_layer._encoder_blocks.0._conv_layers.1.2.weight", "_modeling_layer._encoder_blocks.0._conv_layers.1.2.bias", "_modeling_layer._encoder_blocks.0.attention_norm_layer.weight", "_modeling_layer._encoder_blocks.0.attention_norm_layer.bias", "_modeling_layer._encoder_blocks.0.attention_layer._combined_projection.weight", "_modeling_layer._encoder_blocks.0.attention_layer._combined_projection.bias", "_modeling_layer._encoder_blocks.0.attention_layer._output_projection.weight", "_modeling_layer._encoder_blocks.0.attention_layer._output_projection.bias", "_modeling_layer._encoder_blocks.0.feedforward_norm_layer.weight", "_modeling_layer._encoder_blocks.0.feedforward_norm_layer.bias", "_modeling_layer._encoder_blocks.0.feedforward._linear_layers.0.weight", "_modeling_layer._encoder_blocks.0.feedforward._linear_layers.0.bias", "_modeling_layer._encoder_blocks.0.feedforward._linear_layers.1.weight", "_modeling_layer._encoder_blocks.0.feedforward._linear_layers.1.bias", "_modeling_layer._encoder_blocks.1._conv_norm_layers.0.weight", "_modeling_layer._encoder_blocks.1._conv_norm_layers.0.bias", "_modeling_layer._encoder_blocks.1._conv_norm_layers.1.weight", "_modeling_layer._encoder_blocks.1._conv_norm_layers.1.bias", "_modeling_layer._encoder_blocks.1._conv_layers.0.1.weight", "_modeling_layer._encoder_blocks.1._conv_layers.0.1.bias", "_modeling_layer._encoder_blocks.1._conv_layers.0.2.weight", "_modeling_layer._encoder_blocks.1._conv_layers.0.2.bias", "_modeling_layer._encoder_blocks.1._conv_layers.1.1.weight", "_modeling_layer._encoder_blocks.1._conv_layers.1.1.bias", "_modeling_layer._encoder_blocks.1._conv_layers.1.2.weight", "_modeling_layer._encoder_blocks.1._conv_layers.1.2.bias", "_modeling_layer._encoder_blocks.1.attention_norm_layer.weight", "_modeling_layer._encoder_blocks.1.attention_norm_layer.bias", "_modeling_layer._encoder_blocks.1.attention_layer._combined_projection.weight", "_modeling_layer._encoder_blocks.1.attention_layer._combined_projection.bias", "_modeling_layer._encoder_blocks.1.attention_layer._output_projection.weight", "_modeling_layer._encoder_blocks.1.attention_layer._output_projection.bias", "_modeling_layer._encoder_blocks.1.feedforward_norm_layer.weight", "_modeling_layer._encoder_blocks.1.feedforward_norm_layer.bias", "_modeling_layer._encoder_blocks.1.feedforward._linear_layers.0.weight", "_modeling_layer._encoder_blocks.1.feedforward._linear_layers.0.bias", "_modeling_layer._encoder_blocks.1.feedforward._linear_layers.1.weight", "_modeling_layer._encoder_blocks.1.feedforward._linear_layers.1.bias", "_modeling_layer._encoder_blocks.2._conv_norm_layers.0.weight", "_modeling_layer._encoder_blocks.2._conv_norm_layers.0.bias", "_modeling_layer._encoder_blocks.2._conv_norm_layers.1.weight", "_modeling_layer._encoder_blocks.2._conv_norm_layers.1.bias", "_modeling_layer._encoder_blocks.2._conv_layers.0.1.weight", "_modeling_layer._encoder_blocks.2._conv_layers.0.1.bias", "_modeling_layer._encoder_blocks.2._conv_layers.0.2.weight", "_modeling_layer._encoder_blocks.2._conv_layers.0.2.bias", "_modeling_layer._encoder_blocks.2._conv_layers.1.1.weight", "_modeling_layer._encoder_blocks.2._conv_layers.1.1.bias", "_modeling_layer._encoder_blocks.2._conv_layers.1.2.weight", "_modeling_layer._encoder_blocks.2._conv_layers.1.2.bias", "_modeling_layer._encoder_blocks.2.attention_norm_layer.weight", "_modeling_layer._encoder_blocks.2.attention_norm_layer.bias", "_modeling_layer._encoder_blocks.2.attention_layer._combined_projection.weight", "_modeling_layer._encoder_blocks.2.attention_layer._combined_projection.bias", "_modeling_layer._encoder_blocks.2.attention_layer._output_projection.weight", "_modeling_layer._encoder_blocks.2.attention_layer._output_projection.bias", "_modeling_layer._encoder_blocks.2.feedforward_norm_layer.weight", "_modeling_layer._encoder_blocks.2.feedforward_norm_layer.bias", "_modeling_layer._encoder_blocks.2.feedforward._linear_layers.0.weight", "_modeling_layer._encoder_blocks.2.feedforward._linear_layers.0.bias", "_modeling_layer._encoder_blocks.2.feedforward._linear_layers.1.weight", "_modeling_layer._encoder_blocks.2.feedforward._linear_layers.1.bias", "_modeling_layer._encoder_blocks.3._conv_norm_layers.0.weight", "_modeling_layer._encoder_blocks.3._conv_norm_layers.0.bias", "_modeling_layer._encoder_blocks.3._conv_norm_layers.1.weight", "_modeling_layer._encoder_blocks.3._conv_norm_layers.1.bias", "_modeling_layer._encoder_blocks.3._conv_layers.0.1.weight", "_modeling_layer._encoder_blocks.3._conv_layers.0.1.bias", "_modeling_layer._encoder_blocks.3._conv_layers.0.2.weight", "_modeling_layer._encoder_blocks.3._conv_layers.0.2.bias", "_modeling_layer._encoder_blocks.3._conv_layers.1.1.weight", "_modeling_layer._encoder_blocks.3._conv_layers.1.1.bias", "_modeling_layer._encoder_blocks.3._conv_layers.1.2.weight", "_modeling_layer._encoder_blocks.3._conv_layers.1.2.bias", "_modeling_layer._encoder_blocks.3.attention_norm_layer.weight", "_modeling_layer._encoder_blocks.3.attention_norm_layer.bias", "_modeling_layer._encoder_blocks.3.attention_layer._combined_projection.weight", "_modeling_layer._encoder_blocks.3.attention_layer._combined_projection.bias", "_modeling_layer._encoder_blocks.3.attention_layer._output_projection.weight", "_modeling_layer._encoder_blocks.3.attention_layer._output_projection.bias", "_modeling_layer._encoder_blocks.3.feedforward_norm_layer.weight", "_modeling_layer._encoder_blocks.3.feedforward_norm_layer.bias", "_modeling_layer._encoder_blocks.3.feedforward._linear_layers.0.weight", "_modeling_layer._encoder_blocks.3.feedforward._linear_layers.0.bias", "_modeling_layer._encoder_blocks.3.feedforward._linear_layers.1.weight", "_modeling_layer._encoder_blocks.3.feedforward._linear_layers.1.bias", "_modeling_layer._encoder_blocks.4._conv_norm_layers.0.weight", "_modeling_layer._encoder_blocks.4._conv_norm_layers.0.bias", "_modeling_layer._encoder_blocks.4._conv_norm_layers.1.weight", "_modeling_layer._encoder_blocks.4._conv_norm_layers.1.bias", "_modeling_layer._encoder_blocks.4._conv_layers.0.1.weight", "_modeling_layer._encoder_blocks.4._conv_layers.0.1.bias", "_modeling_layer._encoder_blocks.4._conv_layers.0.2.weight", "_modeling_layer._encoder_blocks.4._conv_layers.0.2.bias", "_modeling_layer._encoder_blocks.4._conv_layers.1.1.weight", "_modeling_layer._encoder_blocks.4._conv_layers.1.1.bias", "_modeling_layer._encoder_blocks.4._conv_layers.1.2.weight", "_modeling_layer._encoder_blocks.4._conv_layers.1.2.bias", "_modeling_layer._encoder_blocks.4.attention_norm_layer.weight", "_modeling_layer._encoder_blocks.4.attention_norm_layer.bias", "_modeling_layer._encoder_blocks.4.attention_layer._combined_projection.weight", "_modeling_layer._encoder_blocks.4.attention_layer._combined_projection.bias", "_modeling_layer._encoder_blocks.4.attention_layer._output_projection.weight", "_modeling_layer._encoder_blocks.4.attention_layer._output_projection.bias", "_modeling_layer._encoder_blocks.4.feedforward_norm_layer.weight", "_modeling_layer._encoder_blocks.4.feedforward_norm_layer.bias", "_modeling_layer._encoder_blocks.4.feedforward._linear_layers.0.weight", "_modeling_layer._encoder_blocks.4.feedforward._linear_layers.0.bias", "_modeling_layer._encoder_blocks.4.feedforward._linear_layers.1.weight", "_modeling_layer._encoder_blocks.4.feedforward._linear_layers.1.bias", "_modeling_layer._encoder_blocks.5._conv_norm_layers.0.weight", "_modeling_layer._encoder_blocks.5._conv_norm_layers.0.bias", "_modeling_layer._encoder_blocks.5._conv_norm_layers.1.weight", "_modeling_layer._encoder_blocks.5._conv_norm_layers.1.bias", "_modeling_layer._encoder_blocks.5._conv_layers.0.1.weight", "_modeling_layer._encoder_blocks.5._conv_layers.0.1.bias", "_modeling_layer._encoder_blocks.5._conv_layers.0.2.weight", "_modeling_layer._encoder_blocks.5._conv_layers.0.2.bias", "_modeling_layer._encoder_blocks.5._conv_layers.1.1.weight", "_modeling_layer._encoder_blocks.5._conv_layers.1.1.bias", "_modeling_layer._encoder_blocks.5._conv_layers.1.2.weight", "_modeling_layer._encoder_blocks.5._conv_layers.1.2.bias", "_modeling_layer._encoder_blocks.5.attention_norm_layer.weight", "_modeling_layer._encoder_blocks.5.attention_norm_layer.bias", "_modeling_layer._encoder_blocks.5.attention_layer._combined_projection.weight", "_modeling_layer._encoder_blocks.5.attention_layer._combined_projection.bias", "_modeling_layer._encoder_blocks.5.attention_layer._output_projection.weight", "_modeling_layer._encoder_blocks.5.attention_layer._output_projection.bias", "_modeling_layer._encoder_blocks.5.feedforward_norm_layer.weight", "_modeling_layer._encoder_blocks.5.feedforward_norm_layer.bias", "_modeling_layer._encoder_blocks.5.feedforward._linear_layers.0.weight", "_modeling_layer._encoder_blocks.5.feedforward._linear_layers.0.bias", "_modeling_layer._encoder_blocks.5.feedforward._linear_layers.1.weight", "_modeling_layer._encoder_blocks.5.feedforward._linear_layers.1.bias". 
2019-05-03T16:21:19.917065717Z		Unexpected key(s) in state_dict: "_phrase_layer.encoder_block_0._conv_norm_layers.0.weight", "_phrase_layer.encoder_block_0._conv_norm_layers.0.bias", "_phrase_layer.encoder_block_0._conv_norm_layers.1.weight", "_phrase_layer.encoder_block_0._conv_norm_layers.1.bias", "_phrase_layer.encoder_block_0._conv_norm_layers.2.weight", "_phrase_layer.encoder_block_0._conv_norm_layers.2.bias", "_phrase_layer.encoder_block_0._conv_norm_layers.3.weight", "_phrase_layer.encoder_block_0._conv_norm_layers.3.bias", "_phrase_layer.encoder_block_0._conv_layers.0.1.weight", "_phrase_layer.encoder_block_0._conv_layers.0.1.bias", "_phrase_layer.encoder_block_0._conv_layers.0.2.weight", "_phrase_layer.encoder_block_0._conv_layers.0.2.bias", "_phrase_layer.encoder_block_0._conv_layers.1.1.weight", "_phrase_layer.encoder_block_0._conv_layers.1.1.bias", "_phrase_layer.encoder_block_0._conv_layers.1.2.weight", "_phrase_layer.encoder_block_0._conv_layers.1.2.bias", "_phrase_layer.encoder_block_0._conv_layers.2.1.weight", "_phrase_layer.encoder_block_0._conv_layers.2.1.bias", "_phrase_layer.encoder_block_0._conv_layers.2.2.weight", "_phrase_layer.encoder_block_0._conv_layers.2.2.bias", "_phrase_layer.encoder_block_0._conv_layers.3.1.weight", "_phrase_layer.encoder_block_0._conv_layers.3.1.bias", "_phrase_layer.encoder_block_0._conv_layers.3.2.weight", "_phrase_layer.encoder_block_0._conv_layers.3.2.bias", "_phrase_layer.encoder_block_0.attention_norm_layer.weight", "_phrase_layer.encoder_block_0.attention_norm_layer.bias", "_phrase_layer.encoder_block_0.attention_layer._combined_projection.weight", "_phrase_layer.encoder_block_0.attention_layer._combined_projection.bias", "_phrase_layer.encoder_block_0.attention_layer._output_projection.weight", "_phrase_layer.encoder_block_0.attention_layer._output_projection.bias", "_phrase_layer.encoder_block_0.feedforward_norm_layer.weight", "_phrase_layer.encoder_block_0.feedforward_norm_layer.bias", "_phrase_layer.encoder_block_0.feedforward._linear_layers.0.weight", "_phrase_layer.encoder_block_0.feedforward._linear_layers.0.bias", "_phrase_layer.encoder_block_0.feedforward._linear_layers.1.weight", "_phrase_layer.encoder_block_0.feedforward._linear_layers.1.bias", "_modeling_layer.encoder_block_0._conv_norm_layers.0.weight", "_modeling_layer.encoder_block_0._conv_norm_layers.0.bias", "_modeling_layer.encoder_block_0._conv_norm_layers.1.weight", "_modeling_layer.encoder_block_0._conv_norm_layers.1.bias", "_modeling_layer.encoder_block_0._conv_layers.0.1.weight", "_modeling_layer.encoder_block_0._conv_layers.0.1.bias", "_modeling_layer.encoder_block_0._conv_layers.0.2.weight", "_modeling_layer.encoder_block_0._conv_layers.0.2.bias", "_modeling_layer.encoder_block_0._conv_layers.1.1.weight", "_modeling_layer.encoder_block_0._conv_layers.1.1.bias", "_modeling_layer.encoder_block_0._conv_layers.1.2.weight", "_modeling_layer.encoder_block_0._conv_layers.1.2.bias", "_modeling_layer.encoder_block_0.attention_norm_layer.weight", "_modeling_layer.encoder_block_0.attention_norm_layer.bias", "_modeling_layer.encoder_block_0.attention_layer._combined_projection.weight", "_modeling_layer.encoder_block_0.attention_layer._combined_projection.bias", "_modeling_layer.encoder_block_0.attention_layer._output_projection.weight", "_modeling_layer.encoder_block_0.attention_layer._output_projection.bias", "_modeling_layer.encoder_block_0.feedforward_norm_layer.weight", "_modeling_layer.encoder_block_0.feedforward_norm_layer.bias", "_modeling_layer.encoder_block_0.feedforward._linear_layers.0.weight", "_modeling_layer.encoder_block_0.feedforward._linear_layers.0.bias", "_modeling_layer.encoder_block_0.feedforward._linear_layers.1.weight", "_modeling_layer.encoder_block_0.feedforward._linear_layers.1.bias", "_modeling_layer.encoder_block_1._conv_norm_layers.0.weight", "_modeling_layer.encoder_block_1._conv_norm_layers.0.bias", "_modeling_layer.encoder_block_1._conv_norm_layers.1.weight", "_modeling_layer.encoder_block_1._conv_norm_layers.1.bias", "_modeling_layer.encoder_block_1._conv_layers.0.1.weight", "_modeling_layer.encoder_block_1._conv_layers.0.1.bias", "_modeling_layer.encoder_block_1._conv_layers.0.2.weight", "_modeling_layer.encoder_block_1._conv_layers.0.2.bias", "_modeling_layer.encoder_block_1._conv_layers.1.1.weight", "_modeling_layer.encoder_block_1._conv_layers.1.1.bias", "_modeling_layer.encoder_block_1._conv_layers.1.2.weight", "_modeling_layer.encoder_block_1._conv_layers.1.2.bias", "_modeling_layer.encoder_block_1.attention_norm_layer.weight", "_modeling_layer.encoder_block_1.attention_norm_layer.bias", "_modeling_layer.encoder_block_1.attention_layer._combined_projection.weight", "_modeling_layer.encoder_block_1.attention_layer._combined_projection.bias", "_modeling_layer.encoder_block_1.attention_layer._output_projection.weight", "_modeling_layer.encoder_block_1.attention_layer._output_projection.bias", "_modeling_layer.encoder_block_1.feedforward_norm_layer.weight", "_modeling_layer.encoder_block_1.feedforward_norm_layer.bias", "_modeling_layer.encoder_block_1.feedforward._linear_layers.0.weight", "_modeling_layer.encoder_block_1.feedforward._linear_layers.0.bias", "_modeling_layer.encoder_block_1.feedforward._linear_layers.1.weight", "_modeling_layer.encoder_block_1.feedforward._linear_layers.1.bias", "_modeling_layer.encoder_block_2._conv_norm_layers.0.weight", "_modeling_layer.encoder_block_2._conv_norm_layers.0.bias", "_modeling_layer.encoder_block_2._conv_norm_layers.1.weight", "_modeling_layer.encoder_block_2._conv_norm_layers.1.bias", "_modeling_layer.encoder_block_2._conv_layers.0.1.weight", "_modeling_layer.encoder_block_2._conv_layers.0.1.bias", "_modeling_layer.encoder_block_2._conv_layers.0.2.weight", "_modeling_layer.encoder_block_2._conv_layers.0.2.bias", "_modeling_layer.encoder_block_2._conv_layers.1.1.weight", "_modeling_layer.encoder_block_2._conv_layers.1.1.bias", "_modeling_layer.encoder_block_2._conv_layers.1.2.weight", "_modeling_layer.encoder_block_2._conv_layers.1.2.bias", "_modeling_layer.encoder_block_2.attention_norm_layer.weight", "_modeling_layer.encoder_block_2.attention_norm_layer.bias", "_modeling_layer.encoder_block_2.attention_layer._combined_projection.weight", "_modeling_layer.encoder_block_2.attention_layer._combined_projection.bias", "_modeling_layer.encoder_block_2.attention_layer._output_projection.weight", "_modeling_layer.encoder_block_2.attention_layer._output_projection.bias", "_modeling_layer.encoder_block_2.feedforward_norm_layer.weight", "_modeling_layer.encoder_block_2.feedforward_norm_layer.bias", "_modeling_layer.encoder_block_2.feedforward._linear_layers.0.weight", "_modeling_layer.encoder_block_2.feedforward._linear_layers.0.bias", "_modeling_layer.encoder_block_2.feedforward._linear_layers.1.weight", "_modeling_layer.encoder_block_2.feedforward._linear_layers.1.bias", "_modeling_layer.encoder_block_3._conv_norm_layers.0.weight", "_modeling_layer.encoder_block_3._conv_norm_layers.0.bias", "_modeling_layer.encoder_block_3._conv_norm_layers.1.weight", "_modeling_layer.encoder_block_3._conv_norm_layers.1.bias", "_modeling_layer.encoder_block_3._conv_layers.0.1.weight", "_modeling_layer.encoder_block_3._conv_layers.0.1.bias", "_modeling_layer.encoder_block_3._conv_layers.0.2.weight", "_modeling_layer.encoder_block_3._conv_layers.0.2.bias", "_modeling_layer.encoder_block_3._conv_layers.1.1.weight", "_modeling_layer.encoder_block_3._conv_layers.1.1.bias", "_modeling_layer.encoder_block_3._conv_layers.1.2.weight", "_modeling_layer.encoder_block_3._conv_layers.1.2.bias", "_modeling_layer.encoder_block_3.attention_norm_layer.weight", "_modeling_layer.encoder_block_3.attention_norm_layer.bias", "_modeling_layer.encoder_block_3.attention_layer._combined_projection.weight", "_modeling_layer.encoder_block_3.attention_layer._combined_projection.bias", "_modeling_layer.encoder_block_3.attention_layer._output_projection.weight", "_modeling_layer.encoder_block_3.attention_layer._output_projection.bias", "_modeling_layer.encoder_block_3.feedforward_norm_layer.weight", "_modeling_layer.encoder_block_3.feedforward_norm_layer.bias", "_modeling_layer.encoder_block_3.feedforward._linear_layers.0.weight", "_modeling_layer.encoder_block_3.feedforward._linear_layers.0.bias", "_modeling_layer.encoder_block_3.feedforward._linear_layers.1.weight", "_modeling_layer.encoder_block_3.feedforward._linear_layers.1.bias", "_modeling_layer.encoder_block_4._conv_norm_layers.0.weight", "_modeling_layer.encoder_block_4._conv_norm_layers.0.bias", "_modeling_layer.encoder_block_4._conv_norm_layers.1.weight", "_modeling_layer.encoder_block_4._conv_norm_layers.1.bias", "_modeling_layer.encoder_block_4._conv_layers.0.1.weight", "_modeling_layer.encoder_block_4._conv_layers.0.1.bias", "_modeling_layer.encoder_block_4._conv_layers.0.2.weight", "_modeling_layer.encoder_block_4._conv_layers.0.2.bias", "_modeling_layer.encoder_block_4._conv_layers.1.1.weight", "_modeling_layer.encoder_block_4._conv_layers.1.1.bias", "_modeling_layer.encoder_block_4._conv_layers.1.2.weight", "_modeling_layer.encoder_block_4._conv_layers.1.2.bias", "_modeling_layer.encoder_block_4.attention_norm_layer.weight", "_modeling_layer.encoder_block_4.attention_norm_layer.bias", "_modeling_layer.encoder_block_4.attention_layer._combined_projection.weight", "_modeling_layer.encoder_block_4.attention_layer._combined_projection.bias", "_modeling_layer.encoder_block_4.attention_layer._output_projection.weight", "_modeling_layer.encoder_block_4.attention_layer._output_projection.bias", "_modeling_layer.encoder_block_4.feedforward_norm_layer.weight", "_modeling_layer.encoder_block_4.feedforward_norm_layer.bias", "_modeling_layer.encoder_block_4.feedforward._linear_layers.0.weight", "_modeling_layer.encoder_block_4.feedforward._linear_layers.0.bias", "_modeling_layer.encoder_block_4.feedforward._linear_layers.1.weight", "_modeling_layer.encoder_block_4.feedforward._linear_layers.1.bias", "_modeling_layer.encoder_block_5._conv_norm_layers.0.weight", "_modeling_layer.encoder_block_5._conv_norm_layers.0.bias", "_modeling_layer.encoder_block_5._conv_norm_layers.1.weight", "_modeling_layer.encoder_block_5._conv_norm_layers.1.bias", "_modeling_layer.encoder_block_5._conv_layers.0.1.weight", "_modeling_layer.encoder_block_5._conv_layers.0.1.bias", "_modeling_layer.encoder_block_5._conv_layers.0.2.weight", "_modeling_layer.encoder_block_5._conv_layers.0.2.bias", "_modeling_layer.encoder_block_5._conv_layers.1.1.weight", "_modeling_layer.encoder_block_5._conv_layers.1.1.bias", "_modeling_layer.encoder_block_5._conv_layers.1.2.weight", "_modeling_layer.encoder_block_5._conv_layers.1.2.bias", "_modeling_layer.encoder_block_5.attention_norm_layer.weight", "_modeling_layer.encoder_block_5.attention_norm_layer.bias", "_modeling_layer.encoder_block_5.attention_layer._combined_projection.weight", "_modeling_layer.encoder_block_5.attention_layer._combined_projection.bias", "_modeling_layer.encoder_block_5.attention_layer._output_projection.weight", "_modeling_layer.encoder_block_5.attention_layer._output_projection.bias", "_modeling_layer.encoder_block_5.feedforward_norm_layer.weight", "_modeling_layer.encoder_block_5.feedforward_norm_layer.bias", "_modeling_layer.encoder_block_5.feedforward._linear_layers.0.weight", "_modeling_layer.encoder_block_5.feedforward._linear_layers.0.bias", "_modeling_layer.encoder_block_5.feedforward._linear_layers.1.weight", "_modeling_layer.encoder_block_5.feedforward._linear_layers.1.bias". 
```

**Comment by matt-gardner** [comment]
This is because of a change that was made in the main repo.  To spare you the details, you just need to change the model file referenced [here](https://github.com/allenai/drop-leaderboard-example/blob/04521e97aa9b5062c429048f62996f7f68af2bad/run_model.sh#L3) to this: `naqanet-2019.04.29-fixed-weight-names.tar.gz`.

Also, looks like I don't have permissions on this repo, fyi.

**Comment by schmmd** [comment]
@matt-gardner I can make a PR.  I just fixed the permissions so #allennlp has write.

**Comment by gabrielStanovsky** [comment]
I was able to submit this example to the dev leaderboard after merging this, and changing csv to jsons.
